version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build:
    resource_class: medium

    docker:
      - image: node:14.15.4-alpine3.12

    steps:
      - run: apk add -q curl bash git unzip

      - run:
          name: 'Install AWS CLI v2'
          command: |
            set -x
            ./tools/install-awscli.sh

      - run:
          name: 'Print versions'
          command: |
            set -x
            git --version
            node --version
            npm --version
            yarn --version
            aws --version

      - checkout

      - restore_cache:
          name: 'Restore cache'
          keys:
            - cache-covid19_scenarios-v2-{{ arch }}-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile
      - run: cp .env.example .env
      - run: yarn schema:totypes
      - run: yarn eslint --max-warnings=0
      - run: yarn prod:build

      - save_cache:
          name: 'Save cache'
          key: cache-covid19_scenarios-v2-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./.cache
            - ./.build/production/tmp/cache

      - run:
          name: 'Deploy web content to AWS S3'
          command: |
            cd .build/production/web
            aws s3 cp \
              --dryrun \
              --recursive \
              --cache-control "max-age=2592000, public" \
                _next \
                s3://${AWS_S3_BUCKET}/

      - run:
          name: 'Deploy html files to AWS S3'
          command: |
            cd .build/production/web
            find * -type f -name "*.html" -exec bash -c '\
            aws s3 cp \
              --dryrun \
              --cache-control "no-cache" \
              --metadata-directive REPLACE \
                s3://${AWS_S3_BUCKET}/$1 \
                s3://${AWS_S3_BUCKET}/${1%.html}' \
            - "{}" \;

      - run:
          name: 'Invalidate Cloudfront cache'
          command: |
            aws cloudfront create-invalidation \
              --dryrun \
              --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} \
              --paths "/*"

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: covid19_scenarios-<< pipeline.git.branch >>
          filters:
            branches:
              only: /^(master|staging|release)$/
